import com.google.protobuf.gradle.id

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.google.protobuf") version "0.9.4"
    id("org.apache.pekko.grpc.gradle") version "1.2.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    api(platform("org.apache.pekko:pekko-bom_2.13:1.6.0"))
    api("org.apache.pekko:pekko-actor-typed_2.13")
    implementation("org.apache.pekko:pekko-cluster-sharding-typed_2.13")
    implementation("org.apache.pekko:pekko-persistence-typed_2.13")
    implementation("org.apache.pekko:pekko-serialization-jackson_2.13")
    implementation("org.apache.pekko:pekko-stream_2.13")
    implementation("org.apache.pekko:pekko-slf4j_2.13")
    api("org.apache.pekko:pekko-http_2.13:1.3.0")
    implementation("org.apache.pekko:pekko-persistence-cassandra_2.13:1.1.0")
    implementation("dev.langchain4j:langchain4j-ollama:1.15.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.2")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.19.2")
    implementation("com.microsoft.onnxruntime:onnxruntime:1.26.0")
    implementation("org.apache.tika:tika-core:3.2.3")
    implementation("org.apache.tika:tika-parsers-standard-package:3.2.3")
    implementation("com.google.protobuf:protobuf-java:4.32.1")
    implementation("ai.djl.huggingface:tokenizers:0.35.0")
    implementation("io.grpc:grpc-netty-shaded:1.76.0")
    implementation("io.grpc:grpc-protobuf:1.76.0")
    implementation("io.grpc:grpc-stub:1.76.0")
    implementation("io.grpc:grpc-services:1.76.0")
    implementation("io.opentelemetry:opentelemetry-api:1.45.0")
    implementation("io.opentelemetry:opentelemetry-sdk:1.45.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.45.0")
    compileOnly("org.apache.tomcat:annotations-api:6.0.53")

    runtimeOnly("ch.qos.logback:logback-classic:1.5.18")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.32.1"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.76.0"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                id("grpc")
            }
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named<ProcessResources>("processResources") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

pekkoGrpc {
    generateClient = false
    generateServer = true
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            groupId = "com.example.agent"
            artifactId = "pekko-agent-runtime"
            version = "0.1.0-SNAPSHOT"
        }
    }
}
