pekko {
  loglevel = "INFO"

  actor {
    provider = local

    default-dispatcher {
      fork-join-executor {
        parallelism-min = 4
        parallelism-factor = 2.0
        parallelism-max = 16
      }
      throughput = 10
    }
  }
}
